/* Auto-generated by scripts/gen_pacman_assets.py — do not edit.
 * Arcade Pac-Man tile/sprite/PROM assets (externs).
 * Link: //#link "pacman_assets.c"  and  //#link "pacman_sound.c"
 *
 * Sound driver is relocatable ASM in pacman_sound.c (not fixed __at).
 * Maze tiles are normal CONST.
 */
#ifndef PACMAN_ASSETS_H
#define PACMAN_ASSETS_H

#include "pacman_common.h"

/* RST 10/18/20 from pacman.6e — .db these at 0x0010 in start():
 * 0x85,0x6f,0x3e,0x00,0x8c,0x67,0x7e,0xc9,0x78,0x87,0xd7,0x5f,0x23,0x56,0xeb,0xc9,0xe1,0x87,0xd7,0x5f,0x23,0x56,0xeb,0xe9
 */

void pac_sound_engine(void);
/* NMI secondary entry (ROM 0x2D0C); label inside pac_sound_engine. */
void pac_sound_effects(void);

extern const byte pac_sound_tables[];
extern const byte maze_tiles[868];
extern const byte color_prom[32];
extern const byte palette_prom[256];
extern const byte wave_rom[256];
extern const byte tile_rom[4096];
extern const byte sprite_rom[4096];

#endif
