#!/usr/bin/env python3
"""Export Pengo arcade ROMs into 8bitworkshop include / combined layout.

Reads a MAME rompath directory (files from `mame pengou -listroms` / pengo.cpp)
and writes:

  1) presets/pengo/pengo_rom_assets.h  — C arrays for tiles/sprites/PROMs
  2) optional combined 64KB image for the 8bw Pengo machine

MAME gfx ROMs use ROM_CONTINUE interleave:
  epr-1640.ic92 = tiles bank0 (4KB) + sprites bank0 (4KB)
  epr-1695.ic105 = tiles bank1 (4KB) + sprites bank1 (4KB)

Usage:
  python3 scripts/dump_pengo_roms.py /path/to/mame/roms/pengo
  python3 scripts/dump_pengo_roms.py /path/to/roms --combined out/pengo_assets.rom
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_H = ROOT / "presets" / "pengo" / "pengo_rom_assets.h"

GFX_FILES = (
    ("epr-1640.ic92", "tiles0", "sprites0"),
    ("epr-1695.ic105", "tiles1", "sprites1"),
)
PROM_FILES = (
    ("pr1633.ic78", 0x20, "color_prom"),
    ("pr1634.ic88", 0x400, "lookup_prom"),
    ("pr1635.ic51", 0x100, "wave_rom"),
)


def find_file(romdir: Path, name: str) -> Path:
    direct = romdir / name
    if direct.is_file():
        return direct
    # allow loose files in parent
    alt = romdir.parent / name
    if alt.is_file():
        return alt
    matches = list(romdir.rglob(name))
    if matches:
        return matches[0]
    raise FileNotFoundError(name)


def c_array(name: str, data: bytes, at: int | None = None, per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(lines)
    if at is None:
        return f"const unsigned char {name}[{len(data)}] = {{\n{body}\n}};\n"
    return f"const unsigned char __at(0x{at:04x}) {name}[{len(data)}] = {{\n{body}\n}};\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("romdir", type=Path, help="directory containing Pengo ROM files")
    ap.add_argument("-o", "--header", type=Path, default=DEFAULT_OUT_H, help="output .h path")
    ap.add_argument("--combined", type=Path, help="also write 64KB combined ROM image")
    ap.add_argument("--abs", action="store_true", help="emit __at() placed arrays for linking into 8bw ROM")
    args = ap.parse_args()

    if not args.romdir.is_dir():
        print(f"error: not a directory: {args.romdir}", file=sys.stderr)
        return 1

    chunks: dict[str, bytes] = {}
    for fname, tile_name, spr_name in GFX_FILES:
        raw = find_file(args.romdir, fname).read_bytes()
        if len(raw) != 0x2000:
            print(f"error: {fname} expected 8192 bytes, got {len(raw)}", file=sys.stderr)
            return 1
        chunks[tile_name] = raw[0:0x1000]
        chunks[spr_name] = raw[0x1000:0x2000]
        print(f"  {fname}: {tile_name}+{spr_name}")

    for fname, size, key in PROM_FILES:
        raw = find_file(args.romdir, fname).read_bytes()
        if len(raw) < size:
            print(f"error: {fname} too small ({len(raw)} < {size})", file=sys.stderr)
            return 1
        chunks[key] = raw[:size]
        print(f"  {fname}: {key} ({size} bytes)")

    abs_map = {
        "tiles0": 0x8000,
        "tiles1": 0x9000,
        "sprites0": 0xA000,
        "sprites1": 0xB000,
        "color_prom": 0xC000,
        "lookup_prom": 0xC100,
        "wave_rom": 0xC500,
    }

    parts = [
        "/* Auto-generated by scripts/dump_pengo_roms.py — do not edit. */\n",
        "#ifndef PENGO_ROM_ASSETS_H\n#define PENGO_ROM_ASSETS_H\n\n",
    ]
    for key in ("tiles0", "tiles1", "sprites0", "sprites1", "color_prom", "lookup_prom", "wave_rom"):
        at = abs_map[key] if args.abs else None
        parts.append(c_array(f"pengo_{key}", chunks[key], at))
        parts.append("\n")
    parts.append("#endif\n")

    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text("".join(parts))
    print(f"wrote {args.header}")

    if args.combined:
        img = bytearray(0x10000)
        img[0x8000:0x9000] = chunks["tiles0"]
        img[0x9000:0xA000] = chunks["tiles1"]
        img[0xA000:0xB000] = chunks["sprites0"]
        img[0xB000:0xC000] = chunks["sprites1"]
        img[0xC000:0xC020] = chunks["color_prom"]
        img[0xC100:0xC500] = chunks["lookup_prom"]
        img[0xC500:0xC600] = chunks["wave_rom"]
        args.combined.parent.mkdir(parents=True, exist_ok=True)
        args.combined.write_bytes(img)
        print(f"wrote {args.combined} (program area empty — splice code separately)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
