#!/usr/bin/env python3
"""
Synthesize Pac-ish one-shots and encode as OKI MSM5205 ADPCM (4-bit @ 8 kHz).

Writes:
  presets/pcktgal/adpcm.bin      — packed sample bytes (for ROM $0000+)
  presets/pcktgal/adpcm_map.inc  — ca65 labels: ADPCM_*_OFF / ADPCM_*_LEN

Bank window $4000 maps ROM+0 (bank 0) or ROM+$4000 (bank 1).
Keep samples in the first 16KB so bank stays 0.
"""
from __future__ import annotations

import math
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_BIN = ROOT / "presets/pcktgal/adpcm.bin"
OUT_INC = ROOT / "presets/pcktgal/adpcm_map.inc"
RATE = 8000

# OKI MSM5205 tables
STEP = [
    16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45, 50, 55, 60, 66,
    73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190, 209, 230, 253, 279, 307,
    337, 371, 408, 449, 494, 544, 598, 658, 724, 796, 876, 963, 1060, 1166, 1282, 1411,
    1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871, 5358,
    5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899, 15289, 16818, 18500, 20350,
    22385, 24623, 27086, 29794, 32767,
]
INDEX = [-1, -1, -1, -1, 2, 4, 6, 8]


def clamp16(x: int) -> int:
    return max(-32768, min(32767, x))


def encode_oki(pcm: list[int]) -> bytes:
    """Encode mono int16 PCM → packed OKI ADPCM bytes (high nibble first)."""
    predsample = 0
    index = 0
    nibbles: list[int] = []
    for sample in pcm:
        step = STEP[index]
        diff = sample - predsample
        sign = 0
        if diff < 0:
            sign = 8
            diff = -diff
        nibble = min(7, (diff << 2) // step)  # rough; refine below
        # Standard bit-by-bit
        nibble = 0
        if diff >= step:
            nibble = 4
            diff -= step
        step_h = step >> 1
        if diff >= step_h:
            nibble |= 2
            diff -= step_h
        if diff >= (step_h >> 1):
            nibble |= 1
        nibble |= sign

        # decode path to keep predictor in sync
        diffq = step >> 3
        if nibble & 4:
            diffq += step
        if nibble & 2:
            diffq += step >> 1
        if nibble & 1:
            diffq += step >> 2
        if nibble & 8:
            predsample -= diffq
        else:
            predsample += diffq
        predsample = clamp16(predsample)
        index = max(0, min(48, index + INDEX[nibble & 7]))
        nibbles.append(nibble & 0xF)

    if len(nibbles) & 1:
        nibbles.append(0)
    out = bytearray()
    for i in range(0, len(nibbles), 2):
        out.append((nibbles[i] << 4) | nibbles[i + 1])
    return bytes(out)


def env_ad(n: int, attack: int, decay_start: int) -> list[float]:
    e = []
    for i in range(n):
        if i < attack:
            e.append(i / max(1, attack))
        else:
            t = (i - attack) / max(1, n - attack)
            e.append(max(0.0, 1.0 - t) ** 1.4)
    return e


def synth_tone(seconds: float, freq_fn, wave="tri", vol=0.7) -> list[int]:
    n = int(RATE * seconds)
    attack = max(1, int(RATE * 0.008))
    env = env_ad(n, attack, n)
    out = []
    phase = 0.0
    for i in range(n):
        f = freq_fn(i / max(1, n - 1))
        phase += f / RATE
        ph = phase % 1.0
        if wave == "tri":
            s = 4.0 * abs(ph - 0.5) - 1.0
        elif wave == "sq":
            s = 1.0 if ph < 0.5 else -1.0
        else:  # sine-ish via poly
            s = math.sin(2 * math.pi * ph)
        # soft 2nd harmonic for a bit of body
        s = 0.75 * s + 0.25 * math.sin(4 * math.pi * ph)
        out.append(clamp16(int(s * env[i] * vol * 28000)))
    return out


def make_samples() -> dict[str, bytes]:
    samples: dict[str, bytes] = {}

    # waka1: short rising whoop ~90ms
    samples["WAKA1"] = encode_oki(
        synth_tone(0.09, lambda t: 420 + 380 * t, wave="tri", vol=0.85)
    )
    # waka2: slightly lower
    samples["WAKA2"] = encode_oki(
        synth_tone(0.09, lambda t: 360 + 320 * t, wave="tri", vol=0.85)
    )
    # eat ghost: longer rising sparkle
    samples["EAT"] = encode_oki(
        synth_tone(0.22, lambda t: 300 + 900 * (t ** 0.7), wave="tri", vol=0.9)
    )
    # death: descending whistle ~0.9s
    samples["DEATH"] = encode_oki(
        synth_tone(0.85, lambda t: 1100 * (1.0 - 0.85 * t) + 80, wave="sine", vol=0.8)
    )
    # coin ding: high blip + short fall
    def coin_freq(t: float) -> float:
        return 1400 if t < 0.25 else 900 - 200 * ((t - 0.25) / 0.75)

    samples["COIN"] = encode_oki(synth_tone(0.12, coin_freq, wave="sine", vol=0.9))
    # fruit: quick up-chirp
    samples["FRUIT"] = encode_oki(
        synth_tone(0.11, lambda t: 500 + 700 * t, wave="tri", vol=0.8)
    )
    return samples


def main() -> None:
    samples = make_samples()
    blob = bytearray()
    map_lines = [
        "; Auto-generated by scripts/gen_pcktgal_adpcm.py — OKI MSM5205 @ 8kHz",
        "; Offsets are within bank0 window (CPU $4000 = ROM $0000).",
        "",
    ]
    order = ["WAKA1", "WAKA2", "EAT", "DEATH", "COIN", "FRUIT"]
    for name in order:
        data = samples[name]
        # align 2
        if len(blob) & 1:
            blob.append(0)
        off = len(blob)
        blob += data
        map_lines.append(f"ADPCM_{name}_OFF = ${off:04x}")
        map_lines.append(f"ADPCM_{name}_LEN = ${len(data):04x}")
        map_lines.append("")
        print(f"{name}: {len(data)} bytes ({len(data)*2/RATE:.3f}s) @ ${off:04x}")

    if len(blob) > 0x4000:
        raise SystemExit(f"samples too big for bank0: {len(blob)}")

    OUT_BIN.write_bytes(blob)
    OUT_INC.write_text("\n".join(map_lines) + "\n")
    print(f"wrote {OUT_BIN} ({len(blob)} bytes)")
    print(f"wrote {OUT_INC}")


if __name__ == "__main__":
    main()
